Este notebook contiene los ejercicios de Numpy aplicado al algebra lineal:

        Bootcamp of Data Science with Python [+250 exercises][A-Z]

In [1]:
import numpy as np

In [9]:
Mat = np.array([[1,2,3],[2,1,-1]])
Mat2 = np.array([1,-2,0,3,0,1,4,5,6]).reshape((3,3))
Mat3 = np.array(range(1,10)).reshape(3,3)
Mat4 = np.array([1,4,3]).reshape(-1,1)
print(Mat)
print(Mat2)
print(Mat3)
print(Mat4)

[[ 1  2  3]
 [ 2  1 -1]]
[[ 1 -2  0]
 [ 3  0  1]
 [ 4  5  6]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1]
 [4]
 [3]]


In [13]:
print(np.array(range(1,7)).reshape(-1,1))
print(np.array([1,0,3,-10]))
print(np.array(np.arange(1,6,1)))

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[  1   0   3 -10]
[1 2 3 4 5]


In [21]:
print(np.zeros((2,2), dtype = int))
print(np.zeros((3,5), dtype = int))
print(np.ones((5,5), dtype = int))
print(np.eye(2))
print(np.eye(3))
print(np.eye(6))

[[0 0]
 [0 0]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[1. 0.]
 [0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [28]:
print(np.triu(np.array(range(1,10)).reshape(3,3)))
print(np.tril(np.array(range(1,10)).reshape(3,3)))
print(np.triu(np.array(range(100,125)).reshape(5,5)))

[[1 2 3]
 [0 5 6]
 [0 0 9]]
[[1 0 0]
 [4 5 0]
 [7 8 9]]
[[100 101 102 103 104]
 [  0 106 107 108 109]
 [  0   0 112 113 114]
 [  0   0   0 118 119]
 [  0   0   0   0 124]]


In [39]:
print(np.diag([7,1,-1]))
print(np.diag([3,3,3,3]))
print(np.diag(range(-5,0,1)))
print(np.diag(np.ones(4)*3))

[[ 7  0  0]
 [ 0  1  0]
 [ 0  0 -1]]
[[3 0 0 0]
 [0 3 0 0]
 [0 0 3 0]
 [0 0 0 3]]
[[-5  0  0  0  0]
 [ 0 -4  0  0  0]
 [ 0  0 -3  0  0]
 [ 0  0  0 -2  0]
 [ 0  0  0  0 -1]]
[[3. 0. 0. 0.]
 [0. 3. 0. 0.]
 [0. 0. 3. 0.]
 [0. 0. 0. 3.]]
[3]


In [41]:
A = np.array([[10,11],[5,1],[-2,4]])
B = np.array([[1,25],[3,4],[0,-10]])
print(A+B)

[[11 36]
 [ 8  5]
 [-2 -6]]


In [54]:
A = np.array([[10,11],[5,1],[-2,4]])
B = np.array([[1,25],[3,4],[0,-10]])
C = np.array([[7,3],[6,1],[0,0]])
zero = np.zeros(shape=(3,2))
'''
if A+B == B+A:
    print('La commutatividad es correcta')
elif A+(B+C) == (A+B)+C:
    print('La asociación es correcta')
elif A+0 == A:
    print('0 es la matriz nula')
'''

print(A+B==B+A)
print((A+(B+C))==((A+B)+C))
print(A+zero==A)

[[ True  True]
 [ True  True]
 [ True  True]]
[[ True  True]
 [ True  True]
 [ True  True]]
[[ True  True]
 [ True  True]
 [ True  True]]
