Este notebook contiene los ejercicios de Numpy:

        Bootcamp of Data Science with Python [+250 exercises][A-Z]


In [1]:
# Librerías
import numpy as np

In [2]:
# Ejercicio 1
array = np.array([1, 2, 3, 4, 5])
print('Shape: ', array.shape)
print('Size: ', array.size)
print('Dim: ', array.ndim)
print('NBytes: ', array.nbytes)
print('DTypes: ', array.dtype)

Shape:  (5,)
Size:  5
Dim:  1
NBytes:  40
DTypes:  int64


In [3]:
# Ejercicio 2
def inspect_array(array):
    if isinstance(array, np.ndarray):
        print('Shape: ', array.shape)
        print('Size: ', array.size)
        print('Dim: ', array.ndim)
        print('NBytes: ', array.nbytes)
        print('DTypes: ', array.dtype)
    else:
        print('The objetc is not a array from numpy')

inspect_array(np.array([1, 2, 3, 4, 5]))
print(50*'-')
inspect_array([1,2,3])

Shape:  (5,)
Size:  5
Dim:  1
NBytes:  40
DTypes:  int64
--------------------------------------------------
The objetc is not a array from numpy


In [4]:
# Ejercicio 3 
print(np.array([-1, 4, 7, 9]))
print(np.array(range(1,11)))
print(np.array((10, 11, 12, 13, 14,)))
print(np.array(range(1990,2025,5)))
print(np.array(range(2020,1890,-10)))
print(np.array([100]))

[-1  4  7  9]
[ 1  2  3  4  5  6  7  8  9 10]
[10 11 12 13 14]
[1990 1995 2000 2005 2010 2015 2020]
[2020 2010 2000 1990 1980 1970 1960 1950 1940 1930 1920 1910 1900]
[100]


In [5]:
# Ejercicio 4
print(np.ones(10))
print(np.ones((4,4)))
print(np.ones((3,2), dtype = int))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1 1]
 [1 1]
 [1 1]]


In [6]:
# Ejercicio 5
print(np.zeros(shape = 10))
print(np.zeros(shape = (2,2)))
print(np.zeros((4,6), dtype = float))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [7]:
# Ejercicio 6
ar1 = np.array([[10], [15], [20], [25], [30], [35], [40], [45]]).reshape(8,1)
ar2 = np.array(range(-50, 0, 5))
ar3 = np.array(range(50, 150, 2)).reshape(5, 10)
print(ar1)
print(ar2)
print(ar3)

[[10]
 [15]
 [20]
 [25]
 [30]
 [35]
 [40]
 [45]]
[-50 -45 -40 -35 -30 -25 -20 -15 -10  -5]
[[ 50  52  54  56  58  60  62  64  66  68]
 [ 70  72  74  76  78  80  82  84  86  88]
 [ 90  92  94  96  98 100 102 104 106 108]
 [110 112 114 116 118 120 122 124 126 128]
 [130 132 134 136 138 140 142 144 146 148]]


In [8]:
# Ejercicio 7
print(np.full((1,10),5, dtype = float))
print(np.full((4,4),5, dtype = float))
print(np.full((3,3),3, dtype = float))
print(np.full((10,10),50, dtype = int))

[[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]]
[[5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]]
[[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]]
[[50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]]


In [9]:
# Ejercicio 8
K = np.array([
    [np.nan, 1, 10, 0],
    [np.nan,np.nan,np.nan,np.nan],
    [100, 50, np.nan, -25],
    [30, np.nan, np.nan, 130]])
 
print(np.isnan(K))
print(f'There are {np.isnan(K).sum()} missing data in K.')
print('There are {} missing data in K'.format(np.isnan(K).sum()))

[[ True False False False]
 [ True  True  True  True]
 [False False  True False]
 [False  True  True False]]
There are 8 missing data in K.
There are 8 missing data in K


In [10]:
# Ejercicio 9
np.linspace(1,21,5)

array([ 1.,  6., 11., 16., 21.])

In [11]:
# Ejercicio 10
np.logspace(1,51,10).reshape(-1,1)

array([[1.00000000e+01],
       [3.59381366e+06],
       [1.29154967e+12],
       [4.64158883e+17],
       [1.66810054e+23],
       [5.99484250e+28],
       [2.15443469e+34],
       [7.74263683e+39],
       [2.78255940e+45],
       [1.00000000e+51]])

In [12]:
# Ejercicio 11
np.diag(range(5,31,5))

array([[ 5,  0,  0,  0,  0,  0],
       [ 0, 10,  0,  0,  0,  0],
       [ 0,  0, 15,  0,  0,  0],
       [ 0,  0,  0, 20,  0,  0],
       [ 0,  0,  0,  0, 25,  0],
       [ 0,  0,  0,  0,  0, 30]])

In [13]:
# Ejercicio 12
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [14]:
# Ejercicio 14
array1 = np.arange(1,11)
array2 = np.linspace(1,50,10)
array3 = np.array(range(51))
array4 = np.logspace(1,10,5)
array5 = np.diag(range(5,31,5))
arrays = [array1, array2, array3, array4, array5]
for index, array in enumerate(arrays, start = 1):
    print(f'Sum of the elements of array {index}: ', array.sum())
    


Sum of the elements of array 1:  55
Sum of the elements of array 2:  255.0
Sum of the elements of array 3:  1275
Sum of the elements of array 4:  10056552148.564463
Sum of the elements of array 5:  105


In [15]:
# Ejercicio 15
matrix = np.array(np.random.randint(1,100,15)).reshape(5,3)
print(matrix)
print(matrix.sum())
print(matrix.sum(axis = 0))
print(matrix.sum(axis = 1))

[[69 47 98]
 [ 2 14 31]
 [89 20 62]
 [49 20 53]
 [63 94 94]]
805
[272 195 338]
[214  47 171 122 251]


In [16]:
# Ejercicio 16
array1 = np.array([-1, 10, 3, 4, 7, 27])
array2 = np.random.randint(-100,300,30)
array3 = np.random.randn(10)
array4 = np.array(range(50,10,-2))
arrays = [array1, array2, array3, array4]
for i, array in enumerate (arrays, 1):
    print('The minimun and the maximun is: {},{}'.format(array.min(), array.max()))
    print(f'For the array # {i}, the minimum is {array.min()} and the maximun is {array.max()}')
    print('-'*50)

The minimun and the maximun is: -1,27
For the array # 1, the minimum is -1 and the maximun is 27
--------------------------------------------------
The minimun and the maximun is: -92,277
For the array # 2, the minimum is -92 and the maximun is 277
--------------------------------------------------
The minimun and the maximun is: -1.1020166787848025,0.5225747430258363
For the array # 3, the minimum is -1.1020166787848025 and the maximun is 0.5225747430258363
--------------------------------------------------
The minimun and the maximun is: 12,50
For the array # 4, the minimum is 12 and the maximun is 50
--------------------------------------------------


In [17]:
# Ejercicio 17
def info_array(array):
    print('The maximun value is : ', array.max())
    print('The maximun value per column is : ', array.max(axis = 0))
    print('The maximun value per line is : ', array.max(axis = 1))
    print('The minimun value is : ', array.min())
    print('The minumun value per column is : ', array.min(axis = 0))
    print('The minumun value per line is : ', array.min(axis = 1))

matrix = np.random.randint(-1000,1000,50).reshape(10,5)
info_array(matrix)

The maximun value is :  970
The maximun value per column is :  [970 865 444 806 891]
The maximun value per line is :  [865 891 219 970 435  91 806 686 715 806]
The minimun value is :  -993
The minumun value per column is :  [-988 -910 -993 -991 -873]
The minumun value per line is :  [-135 -910 -873 -991 -993 -860 -333 -683 -545 -593]


In [18]:
# Ejercicio 18
arr = np.random.normal(40,0.5,size = (300))
print('The average is: {}'.format(np.mean(arr)))
print('The median is: {}'.format(np.median(arr)))
print('The standar desviation is: {}'.format(np.std(arr)))
print('The variance is: {}'.format(np.var(arr)))

The average is: 40.008595300079854
The median is: 40.00385662176497
The standar desviation is: 0.4927916791308362
The variance is: 0.24284363902058903


In [19]:
# Ejercicio 19
x = np.random.rand(100)
y = np.random.uniform(size=100)

print('The covariance is :\n', np.cov(x, y))
print('The correlation is :\n', np.corrcoef(x, y))

The covariance is :
 [[0.08993427 0.0011707 ]
 [0.0011707  0.0781391 ]]
The correlation is :
 [[1.         0.01396525]
 [0.01396525 1.        ]]


In [20]:
# Ejercicio 20
A = np.array([[11, 15, 33, 105],
              [1, 140, 45, 90],
              [67, 230, 78, 99]])
print(np.argmax(A))
print(A.argmax())

9
9


In [21]:
B = np.array([
    [73, 22, 20, 62,  3],
    [68, 84, 27, 59, 93],
    [48, 52,  4, 55, 50],
    [42, 23, 63, 67,  4],
    [44, 30, 41, 31, 29]])
print(np.argmin(A))
print(A.argmin())

4
4


In [22]:
array = np.array([-57, 101, 270, 130, 144])


def info_array(array):
    if isinstance(array, np.ndarray):
        print('The maximun value is:        ', array.max())
        print('The minumun value is:        ', array.min())
        print('The average is:               {}'.format(np.mean(array)))
        print('The median is:                {}'.format(np.median(array)))
        print('The standar desviation is:    {}'.format(np.std(array)))
        print('The variance is:              {}'.format(np.var(array)))
    else:
        return None
        
info_array(array)        

The maximun value is:         270
The minumun value is:         -57
The average is:               117.6
The median is:                130.0
The standar desviation is:    104.72554607162475
The variance is:              10967.439999999999


In [23]:
A = np.array([
    [1, 3, 3, 4, 5],
    [4, 7, 11, 3, 5],
    [1, 11, 4, 4, 11]])

Aux = np.unique(A)
print(Aux)

[ 1  3  4  5  7 11]


In [24]:
array1 = np.array([10, 20, 30, 40])
array2 = np.array([100, 30, 5, 1, 40, 100, 20, 130, 155,170])

print(array1[0], array1[2], array1[-1])
print(array2[0], array2[2], array2[-1])

array11 = array1[::-1]
print(array1)

array22 = array2[::-1]
print(array2)

var = array1[1] + array2[-4]
print(var)

10 30 40
100 5 170
[10 20 30 40]
[100  30   5   1  40 100  20 130 155 170]
40


In [25]:
ar = np.array([[-1, 33, 44, 9, 1],[11, 1, 0, 90, 44]])
print(ar)
print(ar[0][3])
print(ar[1,3])

[[-1 33 44  9  1]
 [11  1  0 90 44]]
9
90


In [26]:
ar = np.array([
    [[1, 1, 5, 1],
    [1, 1, 1, 9]],
    [[1, 3, 1, 1],
    [1, 1, 21, 1]]
                ])
print(ar)
print(ar[0,0,2])
print(ar[0,1,-1])
print(ar[1,0,1])
print(ar[1,1,2])

[[[ 1  1  5  1]
  [ 1  1  1  9]]

 [[ 1  3  1  1]
  [ 1  1 21  1]]]
5
9
3
21


In [27]:
ar = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
ar2 = ar[1:5]
ar2

array([2, 3, 4, 5])